### ISSUE TITLE
Add some Examples

### ISSUE THREAD

**Issue by FlxPeters** [docteurklein/php-etl#24]
Hi,

i really like this library, but it's hard to understand how it's working if you see it for the first time. 

Ok, there is the /bin folder and the config.sample, but it woud be really cool to have some standard use cases in the Readme.

**Comment by umpirsky** [comment]
Sorry for commenting on this ancient issue, but I agree that removing Pimple from example and using it for only simple csv to json or similar transform can make it a lot easier to get started with. We can keep `config.sample.php` as advanced example of course.

BTW, really awesome lib.
